version: '3.8'

# This file contains additional configuration for the messaging setup
# Use with: docker-compose -f docker-compose.yml -f docker-compose.messaging.yml up

services:
  # Update the extractor service with RabbitMQ connection details
  extractor:
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=hccuser
      - RABBITMQ_PASSWORD=hccpass
      - RABBITMQ_QUEUE=document-events
      - RABBITMQ_EXCHANGE=hcc-extractor
      - RABBITMQ_VHOST=/
      # Run both batch processing and message consumer
      - SERVICE_MODE=both
    command: ["python", "-m", "main", "--mode", "consumer"]
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Add dedicated metrics service for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - hcc-network
    depends_on:
      - api-gateway
      - extractor

  # Add Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana-provisioning:/etc/grafana/provisioning
    networks:
      - hcc-network
    depends_on:
      - prometheus

networks:
  hcc-network:
    driver: bridge