# Static configuration for Traefik
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Log configuration
log:
  level: "INFO"
  format: "common"

# Access logs
accessLog:
  format: "common"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Certificate resolvers configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "your-email@example.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true